AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ozbargainbot

Parameters:
  ozbargainVerbose:
    Type: String
    Default: "false"
  ozbargainAwsRegion:
    Type: String
    Default: "ap-southeast-2"
  # Make sure the rest of these parameters exist in SSM Parameter store
  ozbargainTimestamp:
    Type: String
    Default: "/ozbargain/timestamp"
  ozbargainTimestampFrontpage:
    Type: String
    Default: "/ozbargain/timestamp_frontpage"
  # Choose any webhooks from these slack/discord webhooks below (at least one must exist)
  ozbargainSlackWebhook:
    Type: String
    Default: "/ozbargain/slack_webhook"
  ozbargainSlackWebhookFrontpage:
    Type: String
    Default: "/ozbargain/slack_webhook_frontpage"
  ozbargainDiscordWebhook:
    Type: String
    Default: "/ozbargain/discord_webhook"
  ozbargainDiscordWebhookFrontpage:
    Type: String
    Default: "/ozbargain/discord_webhook_frontpage"

Globals:
  Function:
    Timeout: 60
    Runtime: python3.8

Resources:
  OzBargainBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda_handler.lambda_handler
      Environment:
        Variables:
          OZBARGAIN_VERBOSE: !Ref ozbargainVerbose
          OZBARGAIN_TIMESTAMP_PARAMETER: !Ref ozbargainTimestamp
          OZBARGAIN_TIMESTAMP_FRONTPAGE_PARAMETER: !Ref ozbargainTimestampFrontpage
          OZBARGAIN_AWS_REGION: !Ref ozbargainAwsRegion
          # Choose any of these webhooks below to post to (at least one must exist)
          OZBARGAIN_SLACK_WEBHOOK_PARAMETER: !Ref ozbargainSlackWebhook
          OZBARGAIN_SLACK_WEBHOOK_FRONTPAGE_PARAMETER: !Ref ozbargainSlackWebhookFrontpage
          OZBARGAIN_DISCORD_WEBHOOK_PARAMETER: !Ref ozbargainDiscordWebhook
          OZBARGAIN_DISCORD_WEBHOOK_FRONTPAGE_PARAMETER: !Ref ozbargainDiscordWebhookFrontpage
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Description: Run every 5 minutes
            Enabled: True
            Schedule: 'rate(5 minutes)'
      Policies:
        - Statement:
            - Sid: SSMGetParametersPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
                - ssm:PutParameter
              Resource: !Sub "arn:aws:ssm:${ AWS::Region }:${ AWS::AccountId }:parameter/ozbargain/*"
