---
version: "3.7"
services:
  ozbargain:
    image: registry.gitlab.com/sami-group/ozbargain_bot:latest
    init: true
    container_name: ozbargain
    restart: unless-stopped
    volumes:
      - "${DOCKERDIR}/appdata/ozbargain:/config"
    environment:
      OZBARGAIN_SLACK_WEBHOOK: ${OZBARGAIN_SLACK_WEBHOOK}
      OZBARGAIN_SLACK_WEBHOOK_FRONTPAGE: ${OZBARGAIN_SLACK_WEBHOOK_FRONTPAGE}
      PUID: 1000
      PGID: 1000
      # OZBARGAIN_TIMESTAMP_OVERRIDE: 2
      RUN_ON_BOOT: asf
