AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ozbargainbot

Parameters:
  verbose:
    Type: String
    Default: "false"
  # Make sure the following exist in SSM Parameter store
  ozbargainTimestamp:
    Type: String
    Default: "/ozbargain/timestamp"
  ozbargainCurlCookie:
    Type: String
    Default: "/ozbargain/curl_cookie"
  # Choose either/or of these slack/discord webhooks (at least one must exist)
  ozbargainSlackWebhook:
    Type: String
    Default: "/ozbargain/slack_webhook"
  ozbargainDiscordWebhook:
    Type: String
    Default: "/ozbargain/discord_webhook"
  awsRegion:
    Type: String
    Default: "ap-southeast-2"

Globals:
  Function:
    Timeout: 60
    Runtime: python3.8

Resources:
  OzBargainBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda_handler.lambda_handler
      Environment:
        Variables:
          VERBOSE: !Ref verbose
          OZBARGAIN_TIMESTAMP_PARAMETER: !Ref ozbargainTimestamp
          OZBARGAIN_CURL_COOKIE_PARAMETER: !Ref ozbargainCurlCookie
          AWS_REGION: !Ref awsRegion
          # Choose either/or of these below (at least one must exist)
          OZBARGAIN_SLACK_WEBHOOK_PARAMETER: !Ref ozbargainSlackWebhook
          OZBARGAIN_DISCORD_WEBHOOK_PARAMETER: !Ref ozbargainDiscordWebhook
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Description: Run every minute
            Enabled: True
            Schedule: 'rate(1 minute)'
      Policies:
        - Statement:
            - Sid: SSMGetParametersPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
                - ssm:PutParameter
              Resource: !Sub "arn:aws:ssm:${ AWS::Region }:${ AWS::AccountId }:parameter/ozbargain/*"
